name: black

on:
  push:
    branches:
      - develop

jobs:
  auto_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black  

    - name: Check code formatting with Black
      run: |
        black --check .
        if [ $? -ne 0 ]; then
          echo "Black check failed. Please format your code."
          exit 1
        fi
