name: Deploy Vue.js to S3 and CloudFront

on:
  push:
    paths:
      - 'src/frontend/**'
    branches:
      - main

env:
  AWS_REGION: ap-northeast-3

jobs:
  deploy:
    if: github.repository == 'data-engineering-team4/Lulu'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          cd src/frontend
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync ./src/frontend/dist/ s3://de-4-2-vue/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E12OSHDO6F6EF2 --paths "/*"
